travis:
  secure:
    BINSTAR_TOKEN: F1TtEz1ThPERCKYRVB1Jrm/JPcVKaA3+e7EvMEI0WRjex/CFL2sEeDL8YBIPDe4+YcDB/XCE02C2geV6nix6O5j9g60iq8+iDStrZZSOocesdVDTyXkAiskFT4WI5QNl/fJlqfHh/LP1M3iSzM3yUfYkV1jSblPfVwVOx85bwYJQF/iLPWHoUy4z7xdEuQ074D5h5T9fugn2ZTD/2UbDEmWxAtGtLkgXZ7jyBDK3LA/uxUsaT5sNND4cHpH/6j3+LGYujNSwBnFcXmQCGSqsQqrYCr6HCfTm5BuP093askMpJCrCxC6KrKfq06+6PtcdGXg2A9f9ICl4MTb716idOj8jyZ9gCZNohgkumE6pnDlciorSf8srrxG0gsdMsuhk7fZ+HX6a3YEJ/CiCWOx7Ph0u5j1R/7PxeJ+6XaZkrXOxP9/m4soE91eTmcJoaJMU6UKD36bRoUDQBUYej69/7V1GAGpSsOAgXQFF9OQKEFigV8+IW+IUzI3swnJiuiRTGKkZfLK9avsJi4A3FWVof4utp9RQ3OmOjITD6aOAGSQx88GOo01h6RxyG9Dic6G4vNh9B7hzONCNNO6WiPQJ8Bs3uKqbdkzRY2TOlHBs3syTqHbjQhvf2AfhxbHEN7GhiviD2PI2DQ0hohYatiVZhrn8qeI871f3VxgC6XjDi9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
